# Using the latest MariaDB image as required
FROM mariadb:latest

# Setting environment variables for MariaDB as they are in the server
ENV MYSQL_DATABASE=flaskapp
ENV MYSQL_USER=USER
ENV MYSQL_PASSWORD=1234
ENV MYSQL_ROOT_PASSWORD=

# Copy initialization script into the container
COPY ./init_db.sql /docker-entrypoint-initdb.d/init_db.sql

# Expose the default MariaDB port
EXPOSE 3306

# Set the entrypoint
ENTRYPOINT ["docker-entrypoint.sh"]

# Start the MariaDB service
CMD ["mysqld"]

