# Using the latest official Nginx image
FROM nginx:latest

# Removing default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copying the servers Nginx configuration file 
COPY ./nginx.conf /etc/nginx/nginx.conf

# Exposing the ports to internet(also for ssl)
EXPOSE 80
EXPOSE 443

# bash comman to start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]

